### ISSUE TITLE
feature request,  extract comment  from create table SQL for each column

### ISSUE THREAD

**Issue by calvin2021y** [marcobambini/sqlite-createtable-parser#1]
sqlite not support `COMMENT` like mysql, but it keep the COMMENT after `--`

```SQL
CREATE TABLE User
        -- A table comment
(
        uid INTEGER,    -- A field comment
        flags INTEGER   -- Another field comment
);
```

If there is some function like `sql3column_comment`  to extract the original comment for each column, will be very useful for migrate manage.

**Comment by marcobambini** [comment]
Let me check what I can do, it seems an useful feature to have.

**Comment by calvin2021y** [comment]
`ADD COLUMN` COMMENT will work like this: 

```
ALTER TABLE `User` ADD COLUMN test -- test 123
INTEGER;
```

**Comment by marcobambini** [comment]
The ALTER TABLE command is not supported. This repo supports CREATE TABLE statements only.

**Comment by calvin2021y** [comment]
After call `ALTER TABLE`,  the `sqlite_master`.`sql`,   will updated like you run a new `CREATE TABLE` sql for current schema,  so no need change for sqlite-createtable-parser.
